### ISSUE TITLE
Need search with subcollection

### ISSUE THREAD

**Issue by venky9885** [asadamatic/firestore_search#20]
Need search with subcollection collection reference

if possible i will try to add it

**Comment by venky9885** [comment]
```
dependencies:
  firestore_search:
    git:
      url: https://github.com/venky9885/firestore_search.git
```
